spring:
  application:
    name: maneta
  datasource:
    url: jdbc:postgresql://localhost:5432/maneta
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: maneta-super-secret-key-please-change-in-production-2026
  expiration: 86400000